version: '3.7'
services:
  imagist:
    container_name: imagist
    image:
      registry.cn-hangzhou.aliyuncs.com/litosrc/imagist:latest
    build:
      ./
    volumes:
      - ./p:/workdir/imagist/public/p
    ports:
      - 8090:80