version: '3.7'
services:
  redis:
    restart: always
    container_name: Redis
    image:
      redis:6.0
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - /Volumes/QuickDocker/Redis6/data:/data
      - /Volumes/QuickDocker/Redis6/logs:/logs
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"