version: '3.7'
services:
  shadowsocks:
    container_name: shadowsocks
    image: shadowsocks/shadowsocks-libev:v3.3.5
    restart: always
    ports:
      - "8388:8388"
    environment:
      SERVER_ADDR: 0.0.0.0
      SERVER_PORT: 8388
      PASSWORD: 123456
      METHOD: "aes-256-cfb"